### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ebak** [swiftlang/sourcekit-lsp#1541]
### Description

I have recently tried out the stable tool-chain (installed with `swiftly` on `Manjaro Linux`) with `VSCode` and its `Swift plugin`.
The memory usage of `sourcekit-lsp` easily freezes out the machine.

The machine has 16 CPU threads (8 core with 2 HW threads), but only 8GB RAM.
As I suspect the number of `sourcekit-lsp` threads scales up based on the number of CPU threads.

Is it possible to explicitly limit the `sourcekit-lsp` threads?
(Linux allows to turn off some cores, but that is not too convenient.)

Or would it be possible to also consider available RAM too when spawning `sourcekit-lsp` threads?
E.g. for 8GB of RAM only spawn 3 threads, even if the machine have 256 CPUs.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://130844901

**Comment by ahoppen** [comment]
Hey @ebak,

A couple of questions: 
- How much memory does sourcekit-lsp use on your machine? I would be expecting something <500MB on start up, fairly independent of your CPU core count.
- Does the memory usage of SourceKit-LSP grow over time or does it go up immediately after launching
- Does this also reproduce with a Swift 6 toolchain. We have made significant changes to SourceKit-LSP between 5.10 and 6.0, so the issue might already be fixed.
- Does the memory usage go up on every project that you open or only on specific ones? If so, would you be able to share the project?

**Comment by ebak** [comment]
Hi,

Now I don't have possibility to try it on the machine with 8 CPUs, maybe next week.

> How much memory does sourcekit-lsp use on your machine? I would be expecting something <500MB on start up, fairly independent of your CPU core count.

I attach screenshots of `htop` output, as I see at startup it only consumes 2.8% (I don't know what `htop` means about this percentage.)

![Screenshot from 2024-07-02 10-57-56](https://github.com/swiftlang/sourcekit-lsp/assets/4029399/b6e505d0-93c5-4ea2-90c7-79e76934a8bd)


> Does the memory usage of SourceKit-LSP grow over time or does it go up immediately after launching

Grows over time. As I see build and source browsing is required for it.

![Screenshot from 2024-07-02 11-49-07](https://github.com/swiftlang/sourcekit-lsp/assets/4029399/07e192a1-c7c4-44c9-b28f-82d9a7dee8b9)

> Does this also reproduce with a Swift 6 toolchain. We have made significant changes to SourceKit-LSP between 5.10 and 6.0, so the issue might already be fixed.

Not yet tried out, maybe I'll do when I have possibility to play it around with the system with 8 CPUs.

> Does the memory usage go up on every project that you open or only on specific ones? If so, would you be able to share the project?

Recently I was working with this project (`QtTest`): 
[QtTest.zip](https://github.com/user-attachments/files/16066687/QtTest.zip)

**Comment by ebak** [comment]
Just by editing the same code, the memory usage quickly goes up to 45% (3.6GB maybe):

![Screenshot from 2024-07-02 15-31-16](https://github.com/swiftlang/sourcekit-lsp/assets/4029399/d554da7e-cd62-443c-8915-1098bf3db60d)

Maybe unrelated but `VSCode` usually forgets about the dependent packages:

![VSCode-Screenshot from 2024-07-02 15-36-06](https://github.com/swiftlang/sourcekit-lsp/assets/4029399/2d6b8d57-31da-4cc4-9256-1d954fd9b102)

The dependencies (`Qlift`, `Math`) are sometimes shown up there, sometimes not.

Sad the 8GB RAM is hardly enough for IDE assisted development.
In my case the opened apps almost use up all free memory (Gnome, 2 terminals, 2 file managers, a light weight editor (gedit), an ebook reader for the Swift book, VSCode with Swift instrumentation).
Opening up a Firefox with 1-2 tabs would easily freeze out the system.

**Comment by ahoppen** [comment]
I have been able to reproduce the memory growth by working on the SourceKit-LSP codebase in VS Code on Ubuntu 22.04.

**Comment by ebak** [comment]
Thanks! With the 6.0 or the 5.10 toolchain?  Maybe if this issue doesn't exist in 6.0, this issue could be closed and wait for 6.0 to get stable. (Currently I cannot test.)

**Comment by ahoppen** [comment]
I saw the memory issue with a 6.0 toolchain.

**Comment by iMostfa** [comment]
i think that this issue is happening more after updating  to Xcode 16.
it keeps growing until the whole device get freezed. 

![image](https://github.com/user-attachments/assets/018f1b16-386f-42bb-b87e-074c90b17d91)

**Comment by iMostfa** [comment]
i downloaded Xcode 15, copied the sourceKit inside it, then placed it inside Xcode 16, and it appears to be working, and fixed my issue [until now]

**Comment by ahoppen** [comment]
Oh, that’s interesting that you’re also seeing excessive memory usage on macOS. I haven't seen that before. 

Could you try reproducing the problem, run `leaks --outputGraph=/tmp sourcekit-lsp` and then share the `.memgraph` file that is being generated the command? I’m hoping that will show us where the memory allocations are from.

**Comment by iMostfa** [comment]
@ahoppen i will try, when it happens i'm running against time to kill SourceKit-lsp before my device is freezed 🥶

i can also confirm that since i started using sourcekit-lsp from Xcode 15 the issue isn't appearing

**Comment by ahoppen** [comment]
I think it would be valuable to see the graph when SourceKit-LSP is at ~2GB. That’s already more than it should take and should contain the culprit who’s using the memory.

**Comment by iMostfa** [comment]
@ahoppen 
i just shared it with u over email, thanks for u

**Comment by ahoppen** [comment]
Thanks for sharing the memgraph, @iMostfa 🙏🏽 With it, it was obvious that the failure cause is the same one as https://github.com/swiftlang/sourcekit-lsp/pull/1720.

**Comment by ahoppen** [comment]
I tracked down the memory leak to a bug in libdispatch. The issue should be fixed by https://github.com/swiftlang/swift-corelibs-libdispatch/pull/850.

**Comment by m-buczek** [comment]
This error prevents me from working on Xcode 16.2.

@ahoppen  Is there a chance to fix this bug in Xcode 16.x or do we have to wait for Xcode 17?

I can confirm that the workaround provided by @iMostfa  works (thanks a lot!).

More detailed instructions:
1. **Disable System Integrity Protection**: [Apple Documentation](https://developer.apple.com/documentation/security/disabling-and-enabling-system-integrity-protection)
2. **Get Xcode 15.4**: [Download Link](https://download.developer.apple.com/Developer_Tools/Xcode_15.4/Xcode_15.4.xip) (requires login to a developer account) and unzip archive.
3. **Replace `sourcekit-lsp` binary**:
```bash
sudo cp /<PATH_TO_XCODE_15.4>/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/

```

**Please note that Xcode will only work with System Integrity Protection disabled.**

**Comment by iMostfa** [comment]
@m-buczek it's interesting that you needed SIP to be disabled, for me it worked without disabling it.
btw @ahoppen can you confirm to us if the changes to sourcekit-lsp were merged to Xcode[or swift which later merged to Xcode]

**Comment by ahoppen** [comment]
Thanks for also confirming that my PR above fixes the issue. The fix will be included in Swift 6.1. I can’t speak for Xcode’s release schedule.

**Comment by terraputix** [comment]
Is anyone still having problems with this? 

I am using Swift 6.1 installed via swiftly on Fedora 40 and `sourcekit-lsp` is heavily eating up my memory when working in Swift using VS Code or Zed.

The leaked memory seems to result mostly from `operator new(unsigned long, std::align_val_t) in libstdc++.so.6`.

![Image](https://github.com/user-attachments/assets/acdb7d2d-9bfb-45ba-a0bf-07d1fe13ce46)

![Image](https://github.com/user-attachments/assets/425ae6b0-786f-4a45-b2d9-d86614415ab0)

**Comment by hamishknight** [comment]
@terraputix That seems surprising to me, that would imply we're leaking entire ASTContexts. Do you have a project you can share that reproduces the issue?

**Comment by iMostfa** [comment]
i can confirm that something is leaking again, on Mac OS, sourcekit-lsp took up 48GB of ram. 
unfortunately, i wasn't able to get a mem dump because the whole system freezed

![Image](https://github.com/user-attachments/assets/457ae149-cb99-43dd-97e3-28714976e431)

**Comment by ahoppen** [comment]
The macOS and Linux leak are probably unrelated because the Linux leak seems to be coming from sourcekitd. macOS runs sourcekitd out-of-process, so the leak here must be coming from a leak inside SourceKit-LSP itself.

@iMostfa and @terraputix Could you file separate issues for the leaks you are seeing and include the following information?
- Which version of SourceKit-LSP are you using?
- Is this issue happening for one particular project / on one specific interaction or always? If it is one project, can you share it?
- Do you have a rough rate at which it is leaking? Eg. does it take a minute to leak 1 GB, 5 minutes, one hour, etc.
- @iMostfa If you could take a memory graph when sourcekit-lsp is using, say 10GB, on macOS as described in https://github.com/swiftlang/sourcekit-lsp/blob/main/Contributor%20Documentation/Debugging%20Memory%20Leaks.md#macos, that would be extremely helpful.

**Comment by terraputix** [comment]
@ahoppen, @hamishknight  I created a follow up issue with the desired information in https://github.com/swiftlang/swift/issues/82362.

**Comment by MahdiBM** [comment]
I want to mention I've also been experiencing a lot of leaks for a long time. I was blaming it on Cursor and simply reopen Cursor to fix, but lately noticed It's actually not Cursor. I'll be trying to catch the leak and see if it matches any of the cases reported above.

**Comment by MahdiBM** [comment]
Just a report: I haven't noticed something that I could call a "leak", recently, on macOS.
The memory usage is still somewhat high (~6-12GB in a M1 16GB machine - swap is definitely saving me) but it doesn't just go up indefinitely.
